* Resumen
**** No deberían entrar temas técnicos, sólo temas llamativos y entretenidos que muestren de manera inicial cosas del mundo de desarrollo, UX, testing, data science, etc.
**** El objetivo principal es romper el estigma del mundo de desarrollo: No toca ser genios, no toca saber matemáticas en la mayoría de los casos, y puede llegar a ser muy divertido.
**** No debe haber fricción para entrar a la charla, un link (no sabemos si inscripción), y todo gratis.
**** Una charla es la entrevista a Nathaly, Esteban se ofreció a ser el entrevistador, durará ~20min-30min. Idea porque es bueno que gente de afuera que ha entrado muestre su experiencia.
**** Las charlas deben ser un formato muy TED.
**** Conferencia de aproximadamente 3 horas, 3 charlas cada una de 30 minutos y un panel. Tiempo extra para otras cosas relacionadas como anuncios de sponsors, etc.
**** Esteban revisará Airmeet para ver si esa plataforma sirve para todo lo que tenemos en mente.
**** Para la próxima semana todos los que quieren dar charlas crearán un pull requests con propuestas de charlas, explicar el storytelling, formato, motivos y qué temas se van a tocar. También puede ser en un archivo de Drive o cualquier medio digital o a través del Slack.
**** La próxima sesión será para hablar de las charlas, sponsors, cómo llegar a la gente y Esteban nos contará lo que descubrió de Airmeet.
